# app_config.yml
development:
  host: "localhost:3000"
  valid_source: %w(127.0.0.1)

test:
  host: "localhost:3000"

production:
  host: "hive.cityvoice.com"
  valid_source: %w(173.203.241.73 208.109.181.114 174.37.88.92 173.203.209.51)