--- 
- :version: = 0.8.2
  :name: hpricot
- :version: = 0.6.1
  :name: httparty
- :version: = 1.4.3.1
  :name: nokogiri
- :version: = 2.1.6
  :name: authlogic
- :version: = 19.1.0
  :name: adwords4r
- :version: = 3.0.18
  :name: haml
- :version: = 0.4.0
  :name: i18n
- :version: = 2.3.14
  :source: http://gemcutter.org
  :name: will_paginate
- :version: = 0.1.4
  :source: http://gemcutter.org
  :name: sendgrid
- :version: = 0.8
  :source: http://gemcutter.org
  :name: gchartrb
- :version: = 0.0.3
  :source: http://gemcutter.org
  :name: static-gmaps
- :version: = 2.0.3
  :name: delayed_job
- :version: = 1.0.10
  :name: daemons
- :version: = 2.3.3.0
  :name: exception_notification
- :version: = 1.6.0
  :name: googlecharts
- :version: = 0.6.2
  :name: aws-s3
- :version: = 2.3.3
  :name: paperclip
- :version: = 2.8.1
  :name: facets
- :version: = 2.4.27
  :name: searchlogic
- :version: = 0.4.6
  :name: pdfkit
- :version: = 1.5.3
  :name: fastercsv
- :version: = 2.0.7
  :name: twiliolib
- :version: = 1.4.1
  :name: cancan
- :version: = 1.0.6
  :name: inherited_resources
- :version: 2.3.9
  :name: rails
