--- 
- :name: hpricot
- :source: http://gems.github.com
  :name: johnreilly-activerecord-activesalesforce-adapter
- :name: httparty
- :name: nokogiri
- :name: authlogic
- :name: adwords4r
- :name: haml
- :name: formtastic
- :version: ~> 2.3.11
  :source: http://gemcutter.org
  :name: will_paginate
- :source: http://gemcutter.org
  :name: sendgrid
- :source: http://gemcutter.org
  :name: gchartrb
- :source: http://gemcutter.org
  :name: static-gmaps
- :name: delayed_job
- :version: = 1.0.10
  :name: daemons
- :name: exception_notification
- :name: googlecharts
- :source: http://gemcutter.org
  :name: aws-s3
- :version: 2.3.9
  :name: rails
